# Generated by Django 2.2.3 on 2019-07-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=30)),
                ('crm', models.PositiveIntegerField()),
                ('endereco', models.CharField(max_length=30)),
                ('especialidade', models.CharField(max_length=20)),
                ('regiao', models.CharField(choices=[('Z1', 'Zona Norte'), ('Z2', 'Zona Sul'), ('Z3', 'Zona Leste'), ('Z4', 'Zona Oeste')], max_length=20)),
            ],
        ),
    ]
