# Generated by Django 2.2.3 on 2019-07-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Medico', models.CharField(max_length=30)),
                ('CRM', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=30)),
                ('especialidade', models.CharField(max_length=20)),
                ('regiao', models.CharField(choices=[('Z1', 'Zona Norte'), ('Z2', 'Zona Sul'), ('Z3', 'Zona Leste'), ('Z4', 'Zona Oeste'), ('Z5', 'Centro')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
    ]
