# Generated by Django 2.2.3 on 2019-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190707_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='regiao',
        ),
        migrations.AddField(
            model_name='medico',
            name='regiao_med',
            field=models.CharField(choices=[('AR', 'Água Rasa'), ('AG', 'Anhanguera'), ('AC', 'Aricanduva'), ('AA', 'Artur Alvim'), ('BF', 'Barra Funda'), ('BV', 'Bela Vista'), ('BL', 'Belém'), ('BR', 'Brás'), ('BT', 'Butantã'), ('CC', 'Cachoeirinha'), ('CA', 'Cambuci'), ('CB', 'Campo Belo'), ('CL', 'Campo Limpo'), ('CG', 'Cangaíba'), ('CR', 'Capão Redond'), ('CO', 'Carrão'), ('CV', 'Casa Verde'), ('CM', 'Cidade Ademar'), ('CD', 'Cidade Dutra'), ('CL', 'Cidade Líder'), ('CT', 'Cidade Tiradentes'), ('CS', 'Consolação'), ('DI', 'Diadema'), ('EM', 'Ermelino Matarazzo'), ('FO', 'Freguesia do Ó'), ('GU', 'Guarujá'), ('GN', 'Guianazes'), ('IG', 'Iguatemi'), ('IP', 'Ipiranga'), ('IB', 'Itaim Bibi'), ('IT', 'Itaquera'), ('JB', 'Jabaquara'), ('JE', 'Jaguaré'), ('JG', 'Jardim Ângela'), ('JP', 'Jardim Paulista'), ('JS', 'Jardim São Luís'), ('LP', 'Lapa'), ('LB', 'Liberdade'), ('LM', 'Limão'), ('MO', 'Moema'), ('MC', 'Mooca'), ('MB', 'Morumbi'), ('PD', 'Pedreira'), ('PN', 'Penha'), ('PI', 'Pinheiros'), ('PB', 'Pirituba'), ('RT', 'Raposo Tavares'), ('RP', 'República'), ('RQ', 'Rio Pequeno'), ('SM', 'Sacomã'), ('SC', 'Santa Cecília'), ('SN', 'Santana'), ('SA', 'Santo Amaro'), ('SD', 'São Domingos'), ('SU', 'Saúde'), ('SE', 'Sé'), ('SO', 'Socorro'), ('TB', 'Tremembé'), ('TC', 'TucuruvI'), ('VA', 'Vila Andrade'), ('VC', 'Vila Curuçá'), ('VF', 'Vila Formosa'), ('VG', 'Vila Guilhermina'), ('VL', 'Vila Leopoldina'), ('VM', 'Vila Matilde'), ('VP', 'Vila Prudente'), ('VS', 'Vila Sônia')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('A', 'Acupuntura'), ('AL', 'Alergia e Imunologia'), ('AN', 'Anestesiologia'), ('AG', 'Angiologia'), ('CC', 'Cancerologia'), ('CD', 'Cardiologia'), ('CM', 'Clínica Médica'), ('DM', 'Dermatologia'), ('EN', 'Endocrinologia'), ('ED', 'Endoscopia'), ('GR', 'Geriatria'), ('GN', 'Ginecologia'), ('HM', 'Hematologia'), ('HO', 'Homeopatia'), ('IF', 'Infectologia'), ('NU', 'Neurologia'), ('OB', 'Obstetrícia'), ('OF', 'Oftalmologia'), ('OT', 'Ortopedia'), ('OR', 'Otorrinolaringologia'), ('PT', 'Patologia'), ('PD', 'Pediatria'), ('PM', 'Pneumologia'), ('PS', 'Psiquiatria'), ('RD', 'Radiologia'), ('RT', 'Radioterapia'), ('RM', 'Reumatologia'), ('UR', 'Urologia')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome_Medico',
            field=models.CharField(default='', max_length=50),
        ),
    ]
