# Generated by Django 2.2.3 on 2019-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190707_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='assunto',
            field=models.CharField(default='', max_length=50),
        ),
    ]
