# Generated by Django 2.2.3 on 2019-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190710_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
