# Generated by Django 2.2.3 on 2019-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190710_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('Acupuntura', 'AC'), ('AlergiaeImunologia', 'AL'), ('Anestesiologia', 'AN'), ('Angiologia', 'AG'), ('Cancerologia', 'CC'), ('Cardiologia', 'CD'), ('Clínica Médica', 'CM'), ('Dermatologia', 'DM'), ('Endocrinologia', 'EN'), ('Endoscopia', 'ED'), ('Geriatria', 'GR'), ('Ginecologia', 'GN'), ('Hematologia', 'HM'), ('Homeopatia', 'HO'), ('Infectologia', 'IF'), ('Neurologia', 'NU'), ('Obstetrícia', 'OB'), ('Oftalmologia', 'OF'), ('Ortopedia', 'OT'), ('Otorrinolaringologia', 'OR'), ('Patologia', 'PT'), ('Pediatria', 'PD'), ('Pneumologia', 'PM'), ('Psiquiatria', 'PS'), ('Radiologia', 'RD'), ('Radioterapia', 'RT'), ('Reumatologia', 'RM'), ('Urologia', 'UR')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='medico',
            name='regiao_med',
            field=models.CharField(choices=[('Água Rasa', 'AR'), ('Anhanguera', 'AG'), ('Aricanduva', 'AC'), ('Artur Alvim', 'AA'), ('Barra Funda', 'BF'), ('Bela Vista', 'BV'), ('Belém', 'BL'), ('Brás', 'BR'), ('Butantã', 'BT'), ('Cachoeirinha', 'CC'), ('Cambuci', 'CA'), ('Campo Belo', 'CB'), ('Campo Limpo', 'CL'), ('Cangaíba', 'CG'), ('Capão Redondo', 'CR'), ('Carrão', 'CO'), ('Casa Verde', 'CV'), ('Cidade Ademar', 'CM'), ('Cidade Dutra', 'CD'), ('Cidade Líder', 'CL'), ('Cidade Tiradentes', 'CT'), ('Consolação', 'CS'), ('Ermelino Matarazzo', 'EM'), ('Freguesia do Ó', 'FO'), ('Guarujá', 'GU'), ('Guianazes', 'GN'), ('Iguatemi', 'IG'), ('Ipiranga', 'IP'), ('Itaim Bibi', 'IB'), ('Itaquera', 'IT'), ('Jabaquara', 'JB'), ('Jaguaré', 'JE'), ('Jardim Ângela', 'JG'), ('Jardim Paulista', 'JP'), ('Jardim São Luís', 'JS'), ('Lapa', 'LP'), ('Liberdade', 'LB'), ('Limão', 'LM'), ('Moema', 'MO'), ('Mooca', 'MC'), ('Morumbi', 'MB'), ('Pedreira', 'PD'), ('Penha', 'PN'), ('Pinheiros', 'PI'), ('Pirituba', 'PB'), ('Raposo Tavares', 'RT'), ('República', 'RP'), ('Rio Pequeno', 'RQ'), ('Sacomã', 'SM'), ('Santa Cecília', 'SC'), ('Santana', 'SN'), ('Santo Amaro', 'SA'), ('São Domingos', 'SD'), ('Saúde', 'SU'), ('Sé', 'SE'), ('Socorro', 'SO'), ('Tucuruvi', 'TC'), ('Vila Andrade', 'VA'), ('Vila Curuçá', 'VC'), ('Vila Formosa', 'VF'), ('Vila Guilhermina', 'VG'), ('Vila Leopoldina', 'VL'), ('Vila Matilde', 'VM'), ('Vila Prudente', 'VP'), ('Vila Sônia', 'VS')], default='', max_length=20),
        ),
    ]
